/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Antonio
 */
public class Empleado extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Empleado() {
        initComponents();
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Text3 = new javax.swing.JLabel();
        pnombre_empleado = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        snombre_empleado = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        papellido_empleado = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text8 = new javax.swing.JLabel();
        sapellido_empleado = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        Text9 = new javax.swing.JLabel();
        cedula_empleado = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        Text4 = new javax.swing.JLabel();
        telefono_empleado = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text11 = new javax.swing.JLabel();
        correo_empleado = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        Text12 = new javax.swing.JLabel();
        direccion_empleado = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        btnaddempleado = new javax.swing.JLabel();
        btnbuscarempleado = new javax.swing.JLabel();
        btneditempleado = new javax.swing.JLabel();
        btnmostrarempleado = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        sapellido_empleado1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        Text13 = new javax.swing.JLabel();
        sapellido_empleado2 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Agregar, Buscar, Modificar y Mostrar Empleados");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 10, 370));

        Text3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text3.setText("Primer Nombre ");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        pnombre_empleado.setForeground(new java.awt.Color(102, 102, 102));
        pnombre_empleado.setText("Ingrese el Primer Nombre del Empleado");
        pnombre_empleado.setBorder(null);
        pnombre_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnombre_empleadoMousePressed(evt);
            }
        });
        pnombre_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnombre_empleadoActionPerformed(evt);
            }
        });
        pnombre_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnombre_empleadoKeyTyped(evt);
            }
        });
        add(pnombre_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 290, 30));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, 10));

        Text6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text6.setText("Segundo Nombre");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, -1));

        snombre_empleado.setForeground(new java.awt.Color(102, 102, 102));
        snombre_empleado.setText("Ingrese el Segundo Nombre del Empleado");
        snombre_empleado.setBorder(null);
        snombre_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                snombre_empleadoMousePressed(evt);
            }
        });
        snombre_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snombre_empleadoActionPerformed(evt);
            }
        });
        snombre_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snombre_empleadoKeyTyped(evt);
            }
        });
        add(snombre_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, 30));

        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, 10));

        Text7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text7.setText("Primer Apellido");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, -1));

        papellido_empleado.setForeground(new java.awt.Color(102, 102, 102));
        papellido_empleado.setText("Ingrese el Primer Apellido del Empleado");
        papellido_empleado.setBorder(null);
        papellido_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                papellido_empleadoMousePressed(evt);
            }
        });
        papellido_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papellido_empleadoActionPerformed(evt);
            }
        });
        papellido_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                papellido_empleadoKeyTyped(evt);
            }
        });
        add(papellido_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 290, 30));

        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, 10));

        Text8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text8.setText("Segundo Apellido");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, -1));

        sapellido_empleado.setForeground(new java.awt.Color(102, 102, 102));
        sapellido_empleado.setText("Ingrese el Segundo Apellido del Empleado");
        sapellido_empleado.setBorder(null);
        sapellido_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sapellido_empleadoMousePressed(evt);
            }
        });
        sapellido_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapellido_empleadoActionPerformed(evt);
            }
        });
        sapellido_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sapellido_empleadoKeyTyped(evt);
            }
        });
        add(sapellido_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 290, 30));

        jSeparator9.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 290, 10));

        Text9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text9.setText("Numero de Documento");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 180, -1));

        cedula_empleado.setForeground(new java.awt.Color(102, 102, 102));
        cedula_empleado.setText("Ingrese el Numero de Documento del Empleado");
        cedula_empleado.setBorder(null);
        cedula_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cedula_empleadoMousePressed(evt);
            }
        });
        cedula_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedula_empleadoActionPerformed(evt);
            }
        });
        cedula_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedula_empleadoKeyTyped(evt);
            }
        });
        add(cedula_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 300, 30));

        jSeparator10.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 300, 10));

        Text4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text4.setText("Telefono");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 110, -1));

        telefono_empleado.setForeground(new java.awt.Color(102, 102, 102));
        telefono_empleado.setText("Ingrese el Telefono del Empleado");
        telefono_empleado.setBorder(null);
        telefono_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                telefono_empleadoMousePressed(evt);
            }
        });
        telefono_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_empleadoActionPerformed(evt);
            }
        });
        telefono_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefono_empleadoKeyTyped(evt);
            }
        });
        add(telefono_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 300, 30));

        jSeparator5.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 300, 10));

        Text11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text11.setText("Correo Electrónico");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 180, -1));

        correo_empleado.setForeground(new java.awt.Color(102, 102, 102));
        correo_empleado.setText("Ingrese el Correo Electronico del Empleado");
        correo_empleado.setBorder(null);
        correo_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correo_empleadoMousePressed(evt);
            }
        });
        correo_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo_empleadoActionPerformed(evt);
            }
        });
        add(correo_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 300, 30));

        jSeparator12.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 300, 10));

        Text12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text12.setText("Dirección");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 140, -1));

        direccion_empleado.setForeground(new java.awt.Color(102, 102, 102));
        direccion_empleado.setText("Ingrese la Dirección del Empleado");
        direccion_empleado.setBorder(null);
        direccion_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                direccion_empleadoMousePressed(evt);
            }
        });
        direccion_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccion_empleadoActionPerformed(evt);
            }
        });
        add(direccion_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 300, 30));

        jSeparator13.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 300, 10));

        btnaddempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addempleado2.png"))); // NOI18N
        btnaddempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddempleadoMouseClicked(evt);
            }
        });
        add(btnaddempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        btnbuscarempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnbuscar.png"))); // NOI18N
        btnbuscarempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarempleadoMouseClicked(evt);
            }
        });
        add(btnbuscarempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, -1, -1));

        btneditempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnedit.png"))); // NOI18N
        btneditempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditempleadoMouseClicked(evt);
            }
        });
        add(btneditempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        btnmostrarempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnmostrar.png"))); // NOI18N
        add(btnmostrarempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        Text10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text10.setText("Usuario");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 150, -1));

        sapellido_empleado1.setForeground(new java.awt.Color(102, 102, 102));
        sapellido_empleado1.setText("Ingrese el Nombre de Usuario");
        sapellido_empleado1.setBorder(null);
        sapellido_empleado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sapellido_empleado1MousePressed(evt);
            }
        });
        sapellido_empleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapellido_empleado1ActionPerformed(evt);
            }
        });
        sapellido_empleado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sapellido_empleado1KeyTyped(evt);
            }
        });
        add(sapellido_empleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 290, 30));

        jSeparator11.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 290, 10));

        Text13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text13.setText("Contraseña");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 150, -1));

        sapellido_empleado2.setForeground(new java.awt.Color(102, 102, 102));
        sapellido_empleado2.setText("Ingrese la Contraseña del Empleado");
        sapellido_empleado2.setBorder(null);
        sapellido_empleado2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sapellido_empleado2MousePressed(evt);
            }
        });
        sapellido_empleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapellido_empleado2ActionPerformed(evt);
            }
        });
        sapellido_empleado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sapellido_empleado2KeyTyped(evt);
            }
        });
        add(sapellido_empleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 290, 30));

        jSeparator14.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 290, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoico5.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void pnombre_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnombre_empleadoMousePressed
    if (pnombre_empleado.getText().equals("Ingrese el Primer Nombre del Empleado")) {
            pnombre_empleado.setText("");
            pnombre_empleado.setForeground(Color.black);
        }
    
    if (snombre_empleado.getText().isEmpty()) {
            snombre_empleado.setText("Ingrese el Segundo Nombre del Empleado");
            snombre_empleado.setForeground(Color.gray);
        }
    
    if (papellido_empleado.getText().isEmpty()) {
            papellido_empleado.setText("Ingrese el Primer Apellido del Empleado");
            papellido_empleado.setForeground(Color.gray);
        }
    
    if (sapellido_empleado.getText().isEmpty()) {
            sapellido_empleado.setText("Ingrese el Segundo Apellido del Empleado");
            sapellido_empleado.setForeground(Color.gray);
        }
    
    if (cedula_empleado.getText().isEmpty()) {
            cedula_empleado.setText("Ingrese el Numero de Documento del Empleado");
            cedula_empleado.setForeground(Color.gray);
        }
    
    if (telefono_empleado.getText().isEmpty()) {
            telefono_empleado.setText("Ingrese el Telefono del Empleado");
            telefono_empleado.setForeground(Color.gray);
        }
    
    if (correo_empleado.getText().isEmpty()) {
            correo_empleado.setText("Ingrese el Correo Electronico del Empleado");
            correo_empleado.setForeground(Color.gray);
        }
    
    if (direccion_empleado.getText().isEmpty()) {
            direccion_empleado.setText("Ingrese la Dirección del Empleado");
            direccion_empleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_pnombre_empleadoMousePressed

    private void pnombre_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnombre_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnombre_empleadoActionPerformed

    private void snombre_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snombre_empleadoMousePressed
    if (snombre_empleado.getText().equals("Ingrese el Segundo Nombre del Empleado")) {
            snombre_empleado.setText("");
            snombre_empleado.setForeground(Color.black);
        }
    
    if (pnombre_empleado.getText().isEmpty()) {
            pnombre_empleado.setText("Ingrese el Primer Nombre del Empleado");
            pnombre_empleado.setForeground(Color.gray);
        }
    
    if (papellido_empleado.getText().isEmpty()) {
            papellido_empleado.setText("Ingrese el Primer Apellido del Empleado");
            papellido_empleado.setForeground(Color.gray);
        }
    
    if (sapellido_empleado.getText().isEmpty()) {
            sapellido_empleado.setText("Ingrese el Segundo Apellido del Empleado");
            sapellido_empleado.setForeground(Color.gray);
        }
    
    if (cedula_empleado.getText().isEmpty()) {
            cedula_empleado.setText("Ingrese el Numero de Documento del Empleado");
            cedula_empleado.setForeground(Color.gray);
        }
    
    if (telefono_empleado.getText().isEmpty()) {
            telefono_empleado.setText("Ingrese el Telefono del Empleado");
            telefono_empleado.setForeground(Color.gray);
        }
    
    if (correo_empleado.getText().isEmpty()) {
            correo_empleado.setText("Ingrese el Correo Electronico del Empleado");
            correo_empleado.setForeground(Color.gray);
        }
    
    if (direccion_empleado.getText().isEmpty()) {
            direccion_empleado.setText("Ingrese la Dirección del Empleado");
            direccion_empleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_snombre_empleadoMousePressed

    private void snombre_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snombre_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snombre_empleadoActionPerformed

    private void papellido_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_papellido_empleadoMousePressed
    if (papellido_empleado.getText().equals("Ingrese el Primer Apellido del Empleado")) {
            papellido_empleado.setText("");
            papellido_empleado.setForeground(Color.black);
        }
    
    if (pnombre_empleado.getText().isEmpty()) {
            pnombre_empleado.setText("Ingrese el Primer Nombre del Empleado");
            pnombre_empleado.setForeground(Color.gray);
        }
    
    if (snombre_empleado.getText().isEmpty()) {
            snombre_empleado.setText("Ingrese el Segundo Nombre del Empleado");
            snombre_empleado.setForeground(Color.gray);
        }
    
    if (sapellido_empleado.getText().isEmpty()) {
            sapellido_empleado.setText("Ingrese el Segundo Apellido del Empleado");
            sapellido_empleado.setForeground(Color.gray);
        }
    
    if (cedula_empleado.getText().isEmpty()) {
            cedula_empleado.setText("Ingrese el Numero de Documento del Empleado");
            cedula_empleado.setForeground(Color.gray);
        }
    
    if (telefono_empleado.getText().isEmpty()) {
            telefono_empleado.setText("Ingrese el Telefono del Empleado");
            telefono_empleado.setForeground(Color.gray);
        }
    
    if (correo_empleado.getText().isEmpty()) {
            correo_empleado.setText("Ingrese el Correo Electronico del Empleado");
            correo_empleado.setForeground(Color.gray);
        }
    
    if (direccion_empleado.getText().isEmpty()) {
            direccion_empleado.setText("Ingrese la Dirección del Empleado");
            direccion_empleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_papellido_empleadoMousePressed

    private void papellido_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papellido_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_papellido_empleadoActionPerformed

    private void sapellido_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sapellido_empleadoMousePressed
    if (sapellido_empleado.getText().equals("Ingrese el Segundo Apellido del Empleado")) {
            sapellido_empleado.setText("");
            sapellido_empleado.setForeground(Color.black);
        }
    
    if (pnombre_empleado.getText().isEmpty()) {
            pnombre_empleado.setText("Ingrese el Primer Nombre del Empleado");
            pnombre_empleado.setForeground(Color.gray);
        }
    
    if (snombre_empleado.getText().isEmpty()) {
            snombre_empleado.setText("Ingrese el Segundo Nombre del Empleado");
            snombre_empleado.setForeground(Color.gray);
        }
    
    if (papellido_empleado.getText().isEmpty()) {
            papellido_empleado.setText("Ingrese el Primer Apellido del Empleado");
            papellido_empleado.setForeground(Color.gray);
        }
    
    if (cedula_empleado.getText().isEmpty()) {
            cedula_empleado.setText("Ingrese el Numero de Documento del Empleado");
            cedula_empleado.setForeground(Color.gray);
        }
    
    if (telefono_empleado.getText().isEmpty()) {
            telefono_empleado.setText("Ingrese el Telefono del Empleado");
            telefono_empleado.setForeground(Color.gray);
        }
    
    if (correo_empleado.getText().isEmpty()) {
            correo_empleado.setText("Ingrese el Correo Electronico del Empleado");
            correo_empleado.setForeground(Color.gray);
        }
    
    if (direccion_empleado.getText().isEmpty()) {
            direccion_empleado.setText("Ingrese la Dirección del Empleado");
            direccion_empleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_sapellido_empleadoMousePressed

    private void sapellido_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapellido_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_empleadoActionPerformed

    private void cedula_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedula_empleadoMousePressed
    if (cedula_empleado.getText().equals("Ingrese el Numero de Documento del Empleado")) {
            cedula_empleado.setText("");
            cedula_empleado.setForeground(Color.black);
        }
    
    if (pnombre_empleado.getText().isEmpty()) {
            pnombre_empleado.setText("Ingrese el Primer Nombre del Empleado");
            pnombre_empleado.setForeground(Color.gray);
        }
    
    if (snombre_empleado.getText().isEmpty()) {
            snombre_empleado.setText("Ingrese el Segundo Nombre del Empleado");
            snombre_empleado.setForeground(Color.gray);
        }
    
    if (sapellido_empleado.getText().isEmpty()) {
            sapellido_empleado.setText("Ingrese el Segundo Apellido del Empleado");
            sapellido_empleado.setForeground(Color.gray);
        }
    
    if (papellido_empleado.getText().isEmpty()) {
            papellido_empleado.setText("Ingrese el Primer Apellido del Empleado");
            papellido_empleado.setForeground(Color.gray);
        }
    
    if (telefono_empleado.getText().isEmpty()) {
            telefono_empleado.setText("Ingrese el Telefono del Empleado");
            telefono_empleado.setForeground(Color.gray);
        }
    
    if (correo_empleado.getText().isEmpty()) {
            correo_empleado.setText("Ingrese el Correo Electronico del Empleado");
            correo_empleado.setForeground(Color.gray);
        }
    
    if (direccion_empleado.getText().isEmpty()) {
            direccion_empleado.setText("Ingrese la Dirección del Empleado");
            direccion_empleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_cedula_empleadoMousePressed

    private void cedula_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedula_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedula_empleadoActionPerformed

    private void telefono_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefono_empleadoMousePressed
    if (telefono_empleado.getText().equals("Ingrese el Telefono del Empleado")) {
            telefono_empleado.setText("");
            telefono_empleado.setForeground(Color.black);
        }
    
    if (pnombre_empleado.getText().isEmpty()) {
            pnombre_empleado.setText("Ingrese el Primer Nombre del Empleado");
            pnombre_empleado.setForeground(Color.gray);
        }
    
    if (snombre_empleado.getText().isEmpty()) {
            snombre_empleado.setText("Ingrese el Segundo Nombre del Empleado");
            snombre_empleado.setForeground(Color.gray);
        }
    
    if (sapellido_empleado.getText().isEmpty()) {
            sapellido_empleado.setText("Ingrese el Segundo Apellido del Empleado");
            sapellido_empleado.setForeground(Color.gray);
        }
    
    if (cedula_empleado.getText().isEmpty()) {
            cedula_empleado.setText("Ingrese el Numero de Documento del Empleado");
            cedula_empleado.setForeground(Color.gray);
        }
    
    if (papellido_empleado.getText().isEmpty()) {
            papellido_empleado.setText("Ingrese el Primer Apellido del Empleado");
            papellido_empleado.setForeground(Color.gray);
        }
    
    if (correo_empleado.getText().isEmpty()) {
            correo_empleado.setText("Ingrese el Correo Electronico del Empleado");
            correo_empleado.setForeground(Color.gray);
        }
    
    if (direccion_empleado.getText().isEmpty()) {
            direccion_empleado.setText("Ingrese la Dirección del Empleado");
            direccion_empleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_telefono_empleadoMousePressed

    private void telefono_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_empleadoActionPerformed

    private void correo_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correo_empleadoMousePressed
    if (correo_empleado.getText().equals("Ingrese el Correo Electronico del Empleado")) {
            correo_empleado.setText("");
            correo_empleado.setForeground(Color.black);
        }
    
    if (pnombre_empleado.getText().isEmpty()) {
            pnombre_empleado.setText("Ingrese el Primer Nombre del Empleado");
            pnombre_empleado.setForeground(Color.gray);
        }
    
    if (snombre_empleado.getText().isEmpty()) {
            snombre_empleado.setText("Ingrese el Segundo Nombre del Empleado");
            snombre_empleado.setForeground(Color.gray);
        }
    
    if (sapellido_empleado.getText().isEmpty()) {
            sapellido_empleado.setText("Ingrese el Segundo Apellido del Empleado");
            sapellido_empleado.setForeground(Color.gray);
        }
    
    if (cedula_empleado.getText().isEmpty()) {
            cedula_empleado.setText("Ingrese el Numero de Documento del Empleado");
            cedula_empleado.setForeground(Color.gray);
        }
    
    if (telefono_empleado.getText().isEmpty()) {
            telefono_empleado.setText("Ingrese el Telefono del Empleado");
            telefono_empleado.setForeground(Color.gray);
        }
    
    if (papellido_empleado.getText().isEmpty()) {
            papellido_empleado.setText("Ingrese el Primer Apellido del Empleado");
            papellido_empleado.setForeground(Color.gray);
        }
    
    if (direccion_empleado.getText().isEmpty()) {
            direccion_empleado.setText("Ingrese la Dirección del Empleado");
            direccion_empleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_correo_empleadoMousePressed

    private void correo_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo_empleadoActionPerformed

    private void direccion_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccion_empleadoMousePressed
    if (direccion_empleado.getText().equals("Ingrese la Dirección del Empleado")) {
            direccion_empleado.setText("");
            direccion_empleado.setForeground(Color.black);
        }
    
    if (pnombre_empleado.getText().isEmpty()) {
            pnombre_empleado.setText("Ingrese el Primer Nombre del Empleado");
            pnombre_empleado.setForeground(Color.gray);
        }
    
    if (snombre_empleado.getText().isEmpty()) {
            snombre_empleado.setText("Ingrese el Segundo Nombre del Empleado");
            snombre_empleado.setForeground(Color.gray);
        }
    
    if (sapellido_empleado.getText().isEmpty()) {
            sapellido_empleado.setText("Ingrese el Segundo Apellido del Empleado");
            sapellido_empleado.setForeground(Color.gray);
        }
    
    if (cedula_empleado.getText().isEmpty()) {
            cedula_empleado.setText("Ingrese el Numero de Documento del Empleado");
            cedula_empleado.setForeground(Color.gray);
        }
    
    if (telefono_empleado.getText().isEmpty()) {
            telefono_empleado.setText("Ingrese el Telefono del Empleado");
            telefono_empleado.setForeground(Color.gray);
        }
    
    if (correo_empleado.getText().isEmpty()) {
            correo_empleado.setText("Ingrese el Correo Electronico del Empleado");
            correo_empleado.setForeground(Color.gray);
        }
    
    if (papellido_empleado.getText().isEmpty()) {
            papellido_empleado.setText("Ingrese el Primer Apellido del Empleado");
            papellido_empleado.setForeground(Color.gray);
        }
    }//GEN-LAST:event_direccion_empleadoMousePressed

    private void direccion_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccion_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccion_empleadoActionPerformed

  
    private void pnombre_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnombre_empleadoKeyTyped
    char c = evt.getKeyChar();
    if((c<'a' || c>'z') &&(c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_pnombre_empleadoKeyTyped

    private void snombre_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snombre_empleadoKeyTyped
    char c = evt.getKeyChar();
    if((c<'a' || c>'z') &&(c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_snombre_empleadoKeyTyped

    private void papellido_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_papellido_empleadoKeyTyped
    char c = evt.getKeyChar();
    if((c<'a' || c>'z') &&(c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_papellido_empleadoKeyTyped

    private void sapellido_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sapellido_empleadoKeyTyped
    char c = evt.getKeyChar();
    if((c<'a' || c>'z') &&(c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_sapellido_empleadoKeyTyped

    private void cedula_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedula_empleadoKeyTyped
    char c = evt.getKeyChar();
    if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_cedula_empleadoKeyTyped

    private void telefono_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefono_empleadoKeyTyped
    char c = evt.getKeyChar();
    if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_telefono_empleadoKeyTyped

    private void btnaddempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddempleadoMouseClicked
        try {
            // TODO add your handling code here:
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            if(correo_empleado.getText().contains("@") && correo_empleado.getText().contains(".")){
                if(telefono_empleado.getText().length()==10){
                    if((snombre_empleado.getText().equals("Ingrese el Segundo Nombre del Empleado") || snombre_empleado.getText().equals("")) && (sapellido_empleado.getText().equals("Ingrese el Segundo Apellido del Empleado")|| sapellido_empleado.getText().equals(""))){
                        String query = "INSERT INTO empleado VALUES ("+Long.parseLong(cedula_empleado.getText().trim())+",'"+pnombre_empleado.getText().trim()+"','','"+papellido_empleado.getText().trim()+"','',"+Long.parseLong(telefono_empleado.getText().trim())+",'"+correo_empleado.getText().trim()+"','"+direccion_empleado.getText().trim()+"')";
                        JOptionPane.showMessageDialog(this, "Registro Exitoso!");
                        con.actualizar(query);
                        
                        con.cerrar();
                        cedula_empleado.setText(null);
                        pnombre_empleado.setText(null);
                        snombre_empleado.setText(null);
                        papellido_empleado.setText(null);
                        sapellido_empleado.setText(null);
                        telefono_empleado.setText(null);
                        correo_empleado.setText(null);
                        direccion_empleado.setText(null);
                    }
                    else if(snombre_empleado.getText().equals("Ingrese el Segundo Nombre del Empleado") || snombre_empleado.getText().equals("")){
                        String query = "INSERT INTO empleado VALUES ("+Long.parseLong(cedula_empleado.getText().trim())+",'"+pnombre_empleado.getText().trim()+"','"+"',"+papellido_empleado.getText().trim()+"','"+sapellido_empleado.getText().trim()+"',"+Long.parseLong(telefono_empleado.getText().trim())+",'"+correo_empleado.getText().trim()+"','"+direccion_empleado.getText().trim()+"')";
                        JOptionPane.showMessageDialog(this, "Registro Exitoso!");
                        con.actualizar(query);
                        
                        con.cerrar();
                        cedula_empleado.setText(null);
                        pnombre_empleado.setText(null);
                        snombre_empleado.setText(null);
                        papellido_empleado.setText(null);
                        sapellido_empleado.setText(null);
                        telefono_empleado.setText(null);
                        correo_empleado.setText(null);
                        direccion_empleado.setText(null);
                    }
                    else if(sapellido_empleado.getText().equals("Ingrese el Segundo Apellido del Empleado")){
                        String query = "INSERT INTO empleado VALUES ("+Long.parseLong(cedula_empleado.getText().trim())+",'"+pnombre_empleado.getText().trim()+"','"+snombre_empleado.getText().trim()+"','"+papellido_empleado.getText().trim()+"','',"+Long.parseLong(telefono_empleado.getText().trim())+",'"+correo_empleado.getText().trim()+"','"+direccion_empleado.getText().trim()+"')";
                        JOptionPane.showMessageDialog(this, "Registro Exitoso!");
                        con.actualizar(query);
                        
                        con.cerrar();
                        cedula_empleado.setText(null);
                        pnombre_empleado.setText(null);
                        snombre_empleado.setText(null);
                        papellido_empleado.setText(null);
                        sapellido_empleado.setText(null);
                        telefono_empleado.setText(null);
                        correo_empleado.setText(null);
                        direccion_empleado.setText(null);
                    }
                    else{
                        String query = "INSERT INTO empleado VALUES ("+Long.parseLong(cedula_empleado.getText().trim())+",'"+pnombre_empleado.getText().trim()+"','"+snombre_empleado.getText().trim()+"','"+papellido_empleado.getText().trim()+"','"+sapellido_empleado.getText().trim()+"',"+Long.parseLong(telefono_empleado.getText().trim())+",'"+correo_empleado.getText().trim()+"','"+direccion_empleado.getText().trim()+"')";
                        JOptionPane.showMessageDialog(this, "Registro Exitoso!");
                        con.actualizar(query);
                        
                        con.cerrar();
                        cedula_empleado.setText(null);
                        pnombre_empleado.setText(null);
                        snombre_empleado.setText(null);
                        papellido_empleado.setText(null);
                        sapellido_empleado.setText(null);
                        telefono_empleado.setText(null);
                        correo_empleado.setText(null);
                        direccion_empleado.setText(null);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Telefono Invalido!");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Correo Invalido!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaddempleadoMouseClicked

    private void btnbuscarempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarempleadoMouseClicked
        // TODO add your handling code here:
        try {
            
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query = "SELECT * FROM empleado WHERE cedula_empleado = "+ Long.parseLong(cedula_empleado.getText().trim());
            ResultSet rs = con.consultar(query);
            
            if(rs.next()){
                
                cedula_empleado.setText(rs.getString("cedula_empleado"));
                pnombre_empleado.setText(rs.getString("pnombre_empleado"));
                snombre_empleado.setText(rs.getString("snombre_empleado"));
                papellido_empleado.setText(rs.getString("papellido_empleado"));
                sapellido_empleado.setText(rs.getString("sapellido_empleado"));
                telefono_empleado.setText(rs.getString("telefono_empleado"));
                correo_empleado.setText(rs.getString("correo_empleado"));
                direccion_empleado.setText(rs.getString("direccion_empleado"));
            }
            else{
                JOptionPane.showMessageDialog(this, "No existe el empleado");
            }
            cedula_empleado.setForeground(Color.BLACK);
                pnombre_empleado.setForeground(Color.BLACK);
                snombre_empleado.setForeground(Color.BLACK);
                papellido_empleado.setForeground(Color.BLACK);
                sapellido_empleado.setForeground(Color.BLACK);
                telefono_empleado.setForeground(Color.BLACK);
                correo_empleado.setForeground(Color.BLACK);
                direccion_empleado.setForeground(Color.BLACK);
                
                con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnbuscarempleadoMouseClicked

    private void btneditempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditempleadoMouseClicked
        try {
            // TODO add your handling code here:
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query = "UPDATE empleado SET pnombre_empleado = '"+pnombre_empleado.getText().trim()+"',snombre_empleado = '"+snombre_empleado.getText().trim()+"', papellido_empleado = '"+papellido_empleado.getText().trim()+"', sapellido_empleado = '"+sapellido_empleado.getText().trim()+"', telefono_empleado = "+Long.parseLong(telefono_empleado.getText().trim())+", correo_empleado = '"+correo_empleado.getText().trim()+"', direccion_empleado = '"+direccion_empleado.getText().trim()+"' WHERE cedula_empleado = "+Long.parseLong(cedula_empleado.getText().trim())+"";
            JOptionPane.showMessageDialog(this, "Datos Actualizaos Correctamente!");
            con.actualizar(query);
            
            con.cerrar();
            cedula_empleado.setText(null);
            pnombre_empleado.setText(null);
            snombre_empleado.setText(null);
            papellido_empleado.setText(null);
            sapellido_empleado.setText(null);
            telefono_empleado.setText(null);
            correo_empleado.setText(null);
            direccion_empleado.setText(null);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditempleadoMouseClicked

    private void sapellido_empleado1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sapellido_empleado1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_empleado1MousePressed

    private void sapellido_empleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapellido_empleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_empleado1ActionPerformed

    private void sapellido_empleado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sapellido_empleado1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_empleado1KeyTyped

    private void sapellido_empleado2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sapellido_empleado2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_empleado2MousePressed

    private void sapellido_empleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapellido_empleado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_empleado2ActionPerformed

    private void sapellido_empleado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sapellido_empleado2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sapellido_empleado2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btnaddempleado;
    private javax.swing.JLabel btnbuscarempleado;
    private javax.swing.JLabel btneditempleado;
    private javax.swing.JLabel btnmostrarempleado;
    private javax.swing.JTextField cedula_empleado;
    private javax.swing.JTextField correo_empleado;
    private javax.swing.JTextField direccion_empleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField papellido_empleado;
    private javax.swing.JTextField pnombre_empleado;
    private javax.swing.JTextField sapellido_empleado;
    private javax.swing.JTextField sapellido_empleado1;
    private javax.swing.JTextField sapellido_empleado2;
    private javax.swing.JTextField snombre_empleado;
    private javax.swing.JTextField telefono_empleado;
    // End of variables declaration//GEN-END:variables
}
