/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Antonio
 */
public class Familia extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Familia() {
        initComponents();
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        codigo_familia = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        nombre_familia = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        descripción_familia = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnagregarfam = new javax.swing.JLabel();
        btnbuscarfam = new javax.swing.JLabel();
        btneditfam = new javax.swing.JLabel();
        btnmostrarfam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Agregar, Buscar, Modificar y Mostrar Familias");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 740, -1));

        Text3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text3.setText("Id Familia");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, -1));

        codigo_familia.setForeground(new java.awt.Color(102, 102, 102));
        codigo_familia.setText("Ingrese el Id de la Familia");
        codigo_familia.setBorder(null);
        codigo_familia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codigo_familiaMousePressed(evt);
            }
        });
        codigo_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_familiaActionPerformed(evt);
            }
        });
        codigo_familia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_familiaKeyTyped(evt);
            }
        });
        add(codigo_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 330, 30));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 330, 10));

        Text6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text6.setText("Nombre Familia");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 140, -1));

        nombre_familia.setForeground(new java.awt.Color(102, 102, 102));
        nombre_familia.setText("Ingrese el Nombre de la Familia");
        nombre_familia.setBorder(null);
        nombre_familia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombre_familiaMousePressed(evt);
            }
        });
        nombre_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_familiaActionPerformed(evt);
            }
        });
        nombre_familia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_familiaKeyTyped(evt);
            }
        });
        add(nombre_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 330, 30));

        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 330, 10));

        Text7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text7.setText("Descripcion Familia");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 190, -1));

        descripción_familia.setForeground(new java.awt.Color(102, 102, 102));
        descripción_familia.setText("Ingrese la Descripcion de la Familia");
        descripción_familia.setBorder(null);
        descripción_familia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                descripción_familiaMousePressed(evt);
            }
        });
        descripción_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripción_familiaActionPerformed(evt);
            }
        });
        add(descripción_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 330, 30));

        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 330, 10));

        btnagregarfam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addfamilia2.png"))); // NOI18N
        btnagregarfam.setToolTipText("");
        btnagregarfam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnagregarfam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarfamMouseClicked(evt);
            }
        });
        add(btnagregarfam, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        btnbuscarfam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarproduct2.png"))); // NOI18N
        btnbuscarfam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnbuscarfam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarfamMouseClicked(evt);
            }
        });
        add(btnbuscarfam, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        btneditfam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnedit.png"))); // NOI18N
        btneditfam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btneditfam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditfamMouseClicked(evt);
            }
        });
        add(btneditfam, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        btnmostrarfam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnmostrar.png"))); // NOI18N
        btnmostrarfam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnmostrarfam, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoico5.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void codigo_familiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigo_familiaMousePressed
    if (codigo_familia.getText().equals("Ingrese el Id de la Familia")) {
            codigo_familia.setText("");
            codigo_familia.setForeground(Color.black);
        }
    
    if (nombre_familia.getText().isEmpty()) {
            nombre_familia.setText("Ingrese el Nombre de la Familia");
            nombre_familia.setForeground(Color.gray);
        }
    
    if (descripción_familia.getText().isEmpty()) {
            descripción_familia.setText("Ingrese la Descripcion de la Familia");
            descripción_familia.setForeground(Color.gray);
        }
    
    
    }//GEN-LAST:event_codigo_familiaMousePressed

    private void codigo_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_familiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_familiaActionPerformed

    private void nombre_familiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_familiaMousePressed
    if (nombre_familia.getText().equals("Ingrese el Nombre de la Familia")) {
            nombre_familia.setText("");
            nombre_familia.setForeground(Color.black);
        }
    
    if (codigo_familia.getText().isEmpty()) {
            codigo_familia.setText("Ingrese el Id de la Familia");
            codigo_familia.setForeground(Color.gray);
        }
    
    if (descripción_familia.getText().isEmpty()) {
            descripción_familia.setText("Ingrese la Descripcion de la Familia");
            descripción_familia.setForeground(Color.gray);
        }
    
    
    }//GEN-LAST:event_nombre_familiaMousePressed

    private void nombre_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_familiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_familiaActionPerformed

    private void descripción_familiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descripción_familiaMousePressed
    if (descripción_familia.getText().equals("Ingrese la Descripcion de la Familia")) {
            descripción_familia.setText("");
            descripción_familia.setForeground(Color.black);
        }
    
    if (codigo_familia.getText().isEmpty()) {
            codigo_familia.setText("Ingrese el Id de la Familia");
            codigo_familia.setForeground(Color.gray);
        }
    
    if (nombre_familia.getText().isEmpty()) {
            nombre_familia.setText("Ingrese el Nombre de la Familia");
            nombre_familia.setForeground(Color.gray);
        }
    
    
    }//GEN-LAST:event_descripción_familiaMousePressed

    private void descripción_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripción_familiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripción_familiaActionPerformed
   
    private void codigo_familiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_familiaKeyTyped
//    char c btnagregartKeyChar();
//    if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_codigo_familiaKeyTyped

    private void nombre_familiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_familiaKeyTyped
    
    }//GEN-LAST:event_nombre_familiaKeyTyped

    private void btnagregarfamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarfamMouseClicked
        try {
            // TODO add your handling code here:
            Conexion con = new Conexion();
            con.ConexionPostgres();
            String query ="INSERT INTO familia VALUES("+ Long.parseLong(codigo_familia.getText().trim())+ ",'" + nombre_familia.getText().trim() + "','" + descripción_familia.getText().trim() +"')";
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            con.actualizar(query);
            
            con.cerrar();
            codigo_familia.setText(null);
            nombre_familia.setText(null);
            descripción_familia.setText(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnagregarfamMouseClicked

    private void btnbuscarfamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarfamMouseClicked
        try {
            // TODO add your handling code here:
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query ="SELECT * FROM familia WHERE id_familia = "+ Integer.parseInt(codigo_familia.getText().trim());
            
            ResultSet rs = con.consultar(query);
            
            if(rs.next()){
                nombre_familia.setText(rs.getString("nombre_familia"));
                descripción_familia.setText(rs.getString("descripcion_familia"));
            }
            else{
                JOptionPane.showMessageDialog(this, "No existe la Familia");
            }
            codigo_familia.setForeground(Color.black);
            nombre_familia.setForeground(Color.black);
            descripción_familia.setForeground(Color.black);
            
            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnbuscarfamMouseClicked

    private void btneditfamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditfamMouseClicked
        try {
            // TODO add your handling code here:
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query ="UPDATE familia SET nombre_familia = '"+nombre_familia.getText().trim()+"', descripcion_familia='"+descripción_familia.getText().trim()+"' WHERE id_familia="+Long.parseLong(codigo_familia.getText().trim());
            JOptionPane.showMessageDialog(this, "Datos Actualizados");
            con.actualizar(query);
            
            con.cerrar();
            codigo_familia.setText(null);
            descripción_familia.setText(null);
            nombre_familia.setText(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditfamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btnagregarfam;
    private javax.swing.JLabel btnbuscarfam;
    private javax.swing.JLabel btneditfam;
    private javax.swing.JLabel btnmostrarfam;
    private javax.swing.JTextField codigo_familia;
    private javax.swing.JTextField descripción_familia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField nombre_familia;
    // End of variables declaration//GEN-END:variables
}
