/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
//import supermercado.agrofacil.Conexion;
//import diseños.Dashboard;
//import static diseños.Dashboard.escritorio;


/**
 *
 * @author Antonio
 */
public class Producto extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Producto() {
        
           
                initComponents();
                try {
                    Conexion con = new Conexion();
                    con.ConexionPostgres();
                    String query ="select * from familia order by id_familia";
                    
                    
                    ResultSet rs=con.consultar(query);
                    
                    while(rs.next())
                    {
                        id_familia.addItem(rs.getLong("id_familia") + "-" + rs.getString("nombre_familia"));
                        
                    }
                    
                    con.cerrar();
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
                
                 try {
                Conexion con = new Conexion();
                con.ConexionPostgres();
                String query ="select * from proveedor order by nit_proveedor";
                ResultSet rs=con.consultar(query);
                while(rs.next())
                {
                    nit_proveedor.addItem(rs.getLong("nit_proveedor") + "-" + rs.getString("nombre_proveedor"));
                    //area_d.addItem(rs.getString("nombre_area"));
                }
                con.cerrar();
                } catch (ClassNotFoundException ex) {
                Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
               Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
                /**
                 * This method is called from within the constructor to initialize the form.
                 * WARNING: Do NOT modify this code. The content of this method is always
                 * regenerated by the Form Editor.
                 */
                @SuppressWarnings("unchecked")
                // <editor-fold defaultstate="collapsed" desc="Generated Code">
                
    
                
    


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Text3 = new javax.swing.JLabel();
        id_producto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        nombre_producto = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        descripcion_producto = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        Text9 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        Text11 = new javax.swing.JLabel();
        stockminimo_producto = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        Text12 = new javax.swing.JLabel();
        existencia_producto = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        id_familia = new javax.swing.JComboBox<>();
        nit_proveedor = new javax.swing.JComboBox<>();
        Text13 = new javax.swing.JLabel();
        valor_producto = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        addproducto = new javax.swing.JLabel();
        buscarproducto = new javax.swing.JLabel();
        editproducto = new javax.swing.JLabel();
        mostrarproducto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Agregar, Buscar, Modificar y Mostrar Productos");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 660, -1));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 10, 290));

        Text3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text3.setText("Id Producto");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        id_producto.setForeground(new java.awt.Color(102, 102, 102));
        id_producto.setText("Ingrese el Id del Producto");
        id_producto.setBorder(null);
        id_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                id_productoMousePressed(evt);
            }
        });
        id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_productoActionPerformed(evt);
            }
        });
        id_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_productoKeyTyped(evt);
            }
        });
        add(id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 10));

        Text6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text6.setText("Nombre Producto");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, -1));

        nombre_producto.setForeground(new java.awt.Color(102, 102, 102));
        nombre_producto.setText("Ingrese el Nombre del Producto");
        nombre_producto.setBorder(null);
        nombre_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombre_productoMousePressed(evt);
            }
        });
        nombre_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_productoActionPerformed(evt);
            }
        });
        nombre_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_productoKeyTyped(evt);
            }
        });
        add(nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 30));

        jSeparator7.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 10));

        Text7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text7.setText("Descripcion Producto");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, -1));

        descripcion_producto.setForeground(new java.awt.Color(102, 102, 102));
        descripcion_producto.setText("Ingrese la Descripcion del Producto");
        descripcion_producto.setBorder(null);
        descripcion_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                descripcion_productoMousePressed(evt);
            }
        });
        descripcion_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcion_productoActionPerformed(evt);
            }
        });
        add(descripcion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, 30));

        jSeparator8.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, 10));

        Text8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text8.setText("Id Familia");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, -1));

        jSeparator9.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 260, 10));

        Text9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text9.setText("Nit Proveedor");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 180, -1));

        jSeparator10.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 300, 10));

        Text11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text11.setText("Strock Minimo Producto");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 180, -1));

        stockminimo_producto.setForeground(new java.awt.Color(102, 102, 102));
        stockminimo_producto.setText("Ingrese el Stock Minimo del Producto");
        stockminimo_producto.setBorder(null);
        stockminimo_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockminimo_productoMousePressed(evt);
            }
        });
        stockminimo_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockminimo_productoActionPerformed(evt);
            }
        });
        stockminimo_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockminimo_productoKeyTyped(evt);
            }
        });
        add(stockminimo_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 300, 30));

        jSeparator12.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 300, 10));

        Text12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text12.setText("Existencia Producto");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 140, -1));

        existencia_producto.setForeground(new java.awt.Color(102, 102, 102));
        existencia_producto.setText("Ingrese la Existencia del Producto");
        existencia_producto.setBorder(null);
        existencia_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                existencia_productoMousePressed(evt);
            }
        });
        existencia_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existencia_productoActionPerformed(evt);
            }
        });
        existencia_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                existencia_productoKeyTyped(evt);
            }
        });
        add(existencia_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 300, 30));

        jSeparator13.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 300, 10));

        id_familia.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        id_familia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        id_familia.setBorder(null);
        id_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_familiaActionPerformed(evt);
            }
        });
        add(id_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 30));

        nit_proveedor.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        nit_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        nit_proveedor.setBorder(null);
        add(nit_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 300, 30));

        Text13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Text13.setText("Valor Producto");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 180, -1));

        valor_producto.setForeground(new java.awt.Color(102, 102, 102));
        valor_producto.setText("Ingrese el Valor del Producto");
        valor_producto.setBorder(null);
        valor_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valor_productoMousePressed(evt);
            }
        });
        valor_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_productoActionPerformed(evt);
            }
        });
        valor_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valor_productoKeyTyped(evt);
            }
        });
        add(valor_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 300, 30));

        jSeparator14.setForeground(new java.awt.Color(51, 153, 255));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 300, 10));

        addproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addproducto2.png"))); // NOI18N
        addproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addproductoMouseClicked(evt);
            }
        });
        add(addproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        buscarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnbuscar2.png"))); // NOI18N
        buscarproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarproductoMouseClicked(evt);
            }
        });
        add(buscarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, 50));

        editproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnedit.png"))); // NOI18N
        editproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editproductoMouseClicked(evt);
            }
        });
        add(editproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        mostrarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnmostrar.png"))); // NOI18N
        mostrarproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(mostrarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoico5.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void descripcion_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descripcion_productoMousePressed
    if (descripcion_producto.getText().equals("Ingrese la Descripcion del Producto")) {
            descripcion_producto.setText("");
            descripcion_producto.setForeground(Color.black);
        }
    
    if (id_producto.getText().isEmpty()) {
            id_producto.setText("Ingrese el Id del Producto");
            id_producto.setForeground(Color.gray);
        }
    
    if (nombre_producto.getText().isEmpty()) {
            nombre_producto.setText("Ingrese el Nombre del Producto");
            nombre_producto.setForeground(Color.gray);
        }
    
    if (stockminimo_producto.getText().isEmpty()) {
            stockminimo_producto.setText("Ingrese el Stock Minimo del Producto");
            stockminimo_producto.setForeground(Color.gray);
        }
    
    if (existencia_producto.getText().isEmpty()) {
            existencia_producto.setText("Ingrese la Existencia del Producto");
            existencia_producto.setForeground(Color.gray);
        }
    
    if (valor_producto.getText().isEmpty()) {
            valor_producto.setText("Ingrese el Valor del Producto");
            valor_producto.setForeground(Color.gray);
        }
    }//GEN-LAST:event_descripcion_productoMousePressed

    private void descripcion_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcion_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcion_productoActionPerformed

    private void stockminimo_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockminimo_productoMousePressed
    if (stockminimo_producto.getText().equals("Ingrese el Stock Minimo del Producto")) {
            stockminimo_producto.setText("");
            stockminimo_producto.setForeground(Color.black);
        }
    
    if (id_producto.getText().isEmpty()) {
            id_producto.setText("Ingrese el Id del Producto");
            id_producto.setForeground(Color.gray);
        }
    
    if (nombre_producto.getText().isEmpty()) {
            nombre_producto.setText("Ingrese el Nombre del Producto");
            nombre_producto.setForeground(Color.gray);
        }
    
    if (descripcion_producto.getText().isEmpty()) {
            descripcion_producto.setText("Ingrese la Descripcion del Producto");
            descripcion_producto.setForeground(Color.gray);
        }
    
    if (existencia_producto.getText().isEmpty()) {
            existencia_producto.setText("Ingrese la Existencia del Producto");
            existencia_producto.setForeground(Color.gray);
        }
    
    if (valor_producto.getText().isEmpty()) {
            valor_producto.setText("Ingrese el Valor del Producto");
            valor_producto.setForeground(Color.gray);
        }
    }//GEN-LAST:event_stockminimo_productoMousePressed

    private void stockminimo_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockminimo_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockminimo_productoActionPerformed

    private void existencia_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existencia_productoMousePressed
    if (existencia_producto.getText().equals("Ingrese la Existencia del Producto")) {
            existencia_producto.setText("");
            existencia_producto.setForeground(Color.black);
        }
    
    if (id_producto.getText().isEmpty()) {
            id_producto.setText("Ingrese el Id del Producto");
            id_producto.setForeground(Color.gray);
        }
    
    if (nombre_producto.getText().isEmpty()) {
            nombre_producto.setText("Ingrese el Nombre del Producto");
            nombre_producto.setForeground(Color.gray);
        }
    
    if (stockminimo_producto.getText().isEmpty()) {
            stockminimo_producto.setText("Ingrese el Stock Minimo del Producto");
            stockminimo_producto.setForeground(Color.gray);
        }
    
    if (descripcion_producto.getText().isEmpty()) {
            descripcion_producto.setText("Ingrese la Descripcion del Producto");
            descripcion_producto.setForeground(Color.gray);
        }
    
    if (valor_producto.getText().isEmpty()) {
            valor_producto.setText("Ingrese el Valor del Producto");
            valor_producto.setForeground(Color.gray);
        }
    }//GEN-LAST:event_existencia_productoMousePressed

    private void existencia_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existencia_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existencia_productoActionPerformed
   
    private void nombre_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_productoActionPerformed

    private void nombre_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_productoMousePressed
        if (nombre_producto.getText().equals("Ingrese el Nombre del Producto")) {
            nombre_producto.setText("");
            nombre_producto.setForeground(Color.black);
        }

        if (id_producto.getText().isEmpty()) {
            id_producto.setText("Ingrese el Id del Producto");
            id_producto.setForeground(Color.gray);
        }

        if (descripcion_producto.getText().isEmpty()) {
            descripcion_producto.setText("Ingrese la Descripcion del Producto");
            descripcion_producto.setForeground(Color.gray);
        }

        if (stockminimo_producto.getText().isEmpty()) {
            stockminimo_producto.setText("Ingrese el Stock Minimo del Producto");
            stockminimo_producto.setForeground(Color.gray);
        }

        if (existencia_producto.getText().isEmpty()) {
            existencia_producto.setText("Ingrese la Existencia del Producto");
            existencia_producto.setForeground(Color.gray);
        }
        
        if (valor_producto.getText().isEmpty()) {
            valor_producto.setText("Ingrese el Valor del Producto");
            valor_producto.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nombre_productoMousePressed

    private void id_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_productoActionPerformed

    private void id_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_productoMousePressed
        if (id_producto.getText().equals("Ingrese el Id del Producto")) {
            id_producto.setText("");
            id_producto.setForeground(Color.black);
        }

        if (nombre_producto.getText().isEmpty()) {
            nombre_producto.setText("Ingrese el Nombre del Producto");
            nombre_producto.setForeground(Color.gray);
        }

        if (descripcion_producto.getText().isEmpty()) {
            descripcion_producto.setText("Ingrese la Descripcion del Producto");
            descripcion_producto.setForeground(Color.gray);
        }

        if (stockminimo_producto.getText().isEmpty()) {
            stockminimo_producto.setText("Ingrese el Stock Minimo del Producto");
            stockminimo_producto.setForeground(Color.gray);
        }

        if (existencia_producto.getText().isEmpty()) {
            existencia_producto.setText("Ingrese la Existencia del Producto");
            existencia_producto.setForeground(Color.gray);
        }
        
        if (valor_producto.getText().isEmpty()) {
            valor_producto.setText("Ingrese el Valor del Producto");
            valor_producto.setForeground(Color.gray);
        }
    }//GEN-LAST:event_id_productoMousePressed

    private void valor_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valor_productoMousePressed
    if (valor_producto.getText().equals("Ingrese el Valor del Producto")) {
            valor_producto.setText("");
            valor_producto.setForeground(Color.black);
        }

        if (nombre_producto.getText().isEmpty()) {
            nombre_producto.setText("Ingrese el Nombre del Producto");
            nombre_producto.setForeground(Color.gray);
        }

        if (descripcion_producto.getText().isEmpty()) {
            descripcion_producto.setText("Ingrese la Descripcion del Producto");
            descripcion_producto.setForeground(Color.gray);
        }

        if (stockminimo_producto.getText().isEmpty()) {
            stockminimo_producto.setText("Ingrese el Stock Minimo del Producto");
            stockminimo_producto.setForeground(Color.gray);
        }

        if (existencia_producto.getText().isEmpty()) {
            existencia_producto.setText("Ingrese la Existencia del Producto");
            existencia_producto.setForeground(Color.gray);
        }
        
        if (id_producto.getText().isEmpty()) {
            id_producto.setText("Ingrese el Id del Producto");
            id_producto.setForeground(Color.gray);
        }
        
        
    }//GEN-LAST:event_valor_productoMousePressed

    private void valor_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_productoActionPerformed

    private void id_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_productoKeyTyped
    char c = evt.getKeyChar();
    if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_id_productoKeyTyped

    private void nombre_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_productoKeyTyped
    
    }//GEN-LAST:event_nombre_productoKeyTyped

    private void stockminimo_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockminimo_productoKeyTyped
    char c = evt.getKeyChar();
    if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_stockminimo_productoKeyTyped

    private void existencia_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_existencia_productoKeyTyped
    char c = evt.getKeyChar();
    if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_existencia_productoKeyTyped

    private void valor_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_productoKeyTyped
    char c = evt.getKeyChar();
    if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_valor_productoKeyTyped

    private void id_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_familiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_familiaActionPerformed

    private void addproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addproductoMouseClicked
        try {
            // TODO add your handling code here:
            String item1 = (String) id_familia.getSelectedItem();
            java.util.StringTokenizer st = new java.util.StringTokenizer(item1, "-");
            String id_f= st.nextToken(); 
            
            String item2 = (String) nit_proveedor.getSelectedItem();
            java.util.StringTokenizer st1 = new java.util.StringTokenizer(item2, "-");
            String nit_p= st1.nextToken(); 
            
            Conexion con = new Conexion();
            con.ConexionPostgres();
            String query ="insert into producto values("+Long.parseLong(id_producto.getText().trim())+",'"+nombre_producto.getText().trim()+"','"+descripcion_producto.getText().trim()+"',"+ Long.parseLong(id_f) +","+ Long.parseLong(nit_p) +","+Long.parseLong(existencia_producto.getText().trim())+","+ Long.parseLong(stockminimo_producto.getText().trim()) +","+ Double.parseDouble(valor_producto.getText().trim()) +")";
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            con.actualizar(query);

            con.cerrar();
            nombre_producto.setText(null);
            id_producto.setText(null);
            descripcion_producto.setText(null);
            stockminimo_producto.setText(null);
            existencia_producto.setText(null);
            valor_producto.setText(null);
            nit_proveedor.setSelectedItem("Seleccione");
            id_familia.setSelectedItem("Seleccione");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addproductoMouseClicked

    private void buscarproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarproductoMouseClicked
        try {
            // TODO add your handling code here:
            Conexion con = new Conexion();
            con.ConexionPostgres();

            String query ="SELECT * FROM producto WHERE id_producto = "+ Long.parseLong(id_producto.getText().trim());

            ResultSet rs = con.consultar(query);

            if(rs.next()){
                nombre_producto.setText(rs.getString("nombre_producto"));
                descripcion_producto.setText(rs.getString("descripcion_producto"));
                stockminimo_producto.setText(rs.getString("stock_minimo_producto"));
                existencia_producto.setText(rs.getString("existencia_producto"));
                valor_producto.setText(rs.getString("valor_producto"));
                
                
            }
            else{
                JOptionPane.showMessageDialog(this, "No existe el Producto");
            }
            id_producto.setForeground(Color.black);
            valor_producto.setForeground(Color.black);
            descripcion_producto.setForeground(Color.black);
            stockminimo_producto.setForeground(Color.black);
            nombre_producto.setForeground(Color.black);
            existencia_producto.setForeground(Color.black);
            con.cerrar();    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarproductoMouseClicked

    private void editproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editproductoMouseClicked
        try {
            // TODO add your handling code here:
            String item1 = (String) id_familia.getSelectedItem();
            java.util.StringTokenizer st = new java.util.StringTokenizer(item1, "-");
            String id_f= st.nextToken(); 
            
            String item2 = (String) nit_proveedor.getSelectedItem();
            java.util.StringTokenizer st1 = new java.util.StringTokenizer(item2, "-");
            String nit_p= st1.nextToken();
            
            Conexion con = new Conexion();
            con.ConexionPostgres();

            String query ="update producto set nombre_producto = '"+ nombre_producto.getText().trim()+"', descripcion_producto='"+descripcion_producto.getText().trim()+"', id_familia="+ Long.parseLong(id_f) +", nit_proveedor="+ Long.parseLong(nit_p) +", stock_minimo_producto="+Long.parseLong(stockminimo_producto.getText().trim())+",existencia_producto="+Long.parseLong(existencia_producto.getText().trim())+", valor_producto="+Long.parseLong(valor_producto.getText().trim())+" where id_producto="+Long.parseLong(id_producto.getText().trim());
            JOptionPane.showMessageDialog(this, "Datos Actualizados");
            con.actualizar(query);

            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Producto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editproductoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel addproducto;
    private javax.swing.JPanel body;
    private javax.swing.JLabel buscarproducto;
    private javax.swing.JTextField descripcion_producto;
    private javax.swing.JLabel editproducto;
    private javax.swing.JTextField existencia_producto;
    private javax.swing.JComboBox<String> id_familia;
    private javax.swing.JTextField id_producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel mostrarproducto;
    private javax.swing.JComboBox<String> nit_proveedor;
    private javax.swing.JTextField nombre_producto;
    private javax.swing.JTextField stockminimo_producto;
    private javax.swing.JTextField valor_producto;
    // End of variables declaration//GEN-END:variables
}
