/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.usuariovista.usuario;
import clases.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antonio
 */
public class Venta extends javax.swing.JPanel {

    private DefaultTableModel model;
    public static java.util.Date hoy = new java.util.Date();
    public static String patron = "dd/MMM/yyyy";

    public static String sfecha;
    public static DateFormat formato1;

    public Insets insets() {
        return super.insets(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * Creates new form Principal
     */
    public Venta() throws Exception {
        initComponents();
        cedula.setText(String.valueOf(Long.parseLong(usuario.getText())));
        Hilo_Lee h = new Hilo_Lee();
        h.inicio();

        //--------------------------------------------------
        //TABLA
        String data3[][] = {};
        String col[] = {"N°", "Cod Producto", "Descripcion", "Cantidad", "Precio", "Tipo Impuesto", "Total"};
        model = new DefaultTableModel(data3, col);
        lista_articulos_table.setModel(model);

        //--------------------------------------------------
        //CAMPOS NO EDITABLES
        fecha_venta.setDate(hoy);
        nombvend_txt.setEnabled(true);
        doc_cliente_txt.setEnabled(true);
        fecha_venta.setEnabled(true);
        id_producto_txt.setEnabled(true);
        cantidad_producto_txt.setEnabled(true);

    }

    public class Hilo_Lee implements Runnable {

        Thread hilo;

        Conexion con;

        public Hilo_Lee() {
        }

        public void inicio() throws Exception {
            con = new Conexion();
            con.ConexionPostgres();

            if (hilo == null) {
                hilo = new Thread(this);//crea el hilo
                //	hilo=new Thread();//crea el hilo
                hilo.start();// lanzar el hilo

            }

        }

        public void stop() {
            hilo = null;
        }

        public void run() {
            String query = "";

            Thread hiloActual = Thread.currentThread();

            while (hilo == hiloActual) {
                try {
                    query = "select max(id_venta) from venta";
                    java.sql.ResultSet rs = con.consultar(query);
                    try {
                        if (rs.next()) {

                            int id = rs.getInt(1) + 1;
                            String idv = String.valueOf(id);
                            id_venta.setText(idv);

                        }
                    } catch (SQLException e) {
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Hilo_Lee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        public void pausa(int tiempo) {
            try {
                Thread.sleep(tiempo);
            } catch (InterruptedException ignorada) {
            }
        }

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        docutxt = new javax.swing.JLabel();
        doc_cliente_txt = new javax.swing.JTextField();
        clientetxt = new javax.swing.JLabel();
        nom_cliente_txt = new javax.swing.JTextField();
        fecha_venta = new com.toedter.calendar.JDateChooser();
        fechatxt1 = new javax.swing.JLabel();
        nombvend_txt = new javax.swing.JTextField();
        vendtxt = new javax.swing.JLabel();
        pagotxt = new javax.swing.JLabel();
        tipopago = new javax.swing.JComboBox<>();
        fechatxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_articulos_table = new javax.swing.JTable();
        cedula = new javax.swing.JLabel();
        nuevaventa_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id_venta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        valor_total = new javax.swing.JLabel();
        id_producto_txt = new javax.swing.JTextField();
        nom_producto_txt = new javax.swing.JTextField();
        cantidad_producto_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        docutxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        docutxt.setText("DOCUMENTO");
        add(docutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        doc_cliente_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doc_cliente_txt.setForeground(new java.awt.Color(204, 204, 204));
        doc_cliente_txt.setText("ingrese la cc o nit");
        doc_cliente_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_cliente_txtActionPerformed(evt);
            }
        });
        add(doc_cliente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 136, -1));

        clientetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientetxt.setText("CLIENTE");
        add(clientetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        nom_cliente_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nom_cliente_txt.setForeground(new java.awt.Color(204, 204, 204));
        nom_cliente_txt.setText("nombre del cliente");
        add(nom_cliente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 182, -1));
        add(fecha_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 190, -1));

        fechatxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechatxt1.setText("FECHA");
        add(fechatxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        nombvend_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombvend_txt.setForeground(new java.awt.Color(204, 204, 204));
        nombvend_txt.setText("nombre vendedor");
        add(nombvend_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 136, -1));

        vendtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vendtxt.setText("VENDEDOR");
        add(vendtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        pagotxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pagotxt.setText("PAGO");
        add(pagotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        tipopago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "CONTADO", "TJ CREDITO", "TJ DEBITO", "BONO" }));
        add(tipopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 136, -1));

        fechatxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechatxt.setText("CEDULA V");
        add(fechatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, 30));

        lista_articulos_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Cod del Articulo", "Descripcion", "Cantidad", "Precio", "Tipo Impuesto", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lista_articulos_table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 652, 190));
        add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 150, 30));

        nuevaventa_btn.setText("Nueva Venta");
        nuevaventa_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaventa_btnActionPerformed(evt);
            }
        });
        add(nuevaventa_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 110, -1));

        jLabel1.setText("FACTURA No.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        id_venta.setText("jLabel2");
        add(id_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, -1));

        jLabel3.setText("cod producto");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel5.setText("nombre producto");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 620, 10));

        jLabel4.setText("cantidad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jLabel6.setText("Total");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        valor_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor_total.setText("0.0");
        add(valor_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 50, -1));
        add(id_producto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 80, -1));
        add(nom_producto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 100, -1));
        add(cantidad_producto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar_producto.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        jButton1.setMnemonic('f');
        jButton1.setText("Facturar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 100, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_agregar_producto .png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void doc_cliente_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_cliente_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_cliente_txtActionPerformed

    private void nuevaventa_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaventa_btnActionPerformed
        // TODO add your handling code here
        try {
        Venta.Hilo_Lee hl=new Venta.Hilo_Lee();
        hl.inicio();
        
        nombvend_txt.setEnabled(true);
        
        DefaultTableModel tb = (DefaultTableModel) lista_articulos_table.getModel();
        int a = lista_articulos_table.getRowCount()-1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount()-1);
        }
        doc_cliente_txt.setText("Ingrese la Cedula del Cliente");
        nombvend_txt.setText("Seleccione");
        id_producto_txt.setText("Ingrese Id");
        cantidad_producto_txt.setText("Ingrese Cantidad");
        valor_total.setText("0.0");
        
        
        
        /*try {
        Conexion con = new Conexion();
        
        con.ConexionPostgres();
        String query = "select max(id_venta) from venta";
        java.sql.ResultSet rs =con.consultar(query);
        if (rs.next()){
        int id = rs.getInt(1) + 1;
        String idv = String.valueOf(id);
        id_venta.setText(idv);
        }
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    } catch (Exception ex) {
        Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_nuevaventa_btnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if(lista_articulos_table.getSelectedRow()>=0){
    DefaultTableModel model =(DefaultTableModel)lista_articulos_table.getModel();
    int rpta = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el producto?","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
    if(rpta == JOptionPane.YES_OPTION){
    model.removeRow(lista_articulos_table.getSelectedRow());
}
}else{
    JOptionPane.showMessageDialog(this,"¡No ha seleccionado ningún producto!","SISTEMA",JOptionPane.WARNING_MESSAGE);
}
    
    int contar=lista_articulos_table.getRowCount();
            double suma=0;
            for(int i=0; i<contar;i++){
            suma=suma+Double.parseDouble(lista_articulos_table.getValueAt(i, 2).toString());
            String sum = Double.toString(suma);
            valor_total.setText(sum);
            
            }
            if(contar==0){
            valor_total.setText("0.0");
            }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Facturar fac = new Facturar();
        fac.setSize(400, 400);
        fac.setLocation(0, 0);
        fac.setVisible(true);
        
        //INSERSION DE DATOS EN LA TABLA VENTA PARA REGISTRAR LA VENTA
//    double vueltos1=Double.parseDouble(recibe.getText().trim())-Double.parseDouble(valor_total.getText());      
//    vueltos.setText(String.valueOf(vueltos1));
            
    
            //------------------------------------------------------------------------
            //INHABILITACION DE LOS CAMPOS UNA VEZ FACTURADO
   
            
            //------------------------------------------------------------------------
            //CONFIRMACION DE LA VENTA

           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
    try {
            if(id_producto_txt.getText().equals("Ingrese Id") || id_producto_txt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese el Id del Producto");
            }else if(cantidad_producto_txt.getText().equals("Ingrese Cantidad") || cantidad_producto_txt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese la Cantidad del Producto");
            }else{
            
            int con1 = 0;
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query = "select * from producto where id_producto = " + Long.parseLong(id_producto_txt.getText().trim());
            
            ResultSet rs = con.consultar(query);
            
            
           

            if (rs.next()) {  
                int cant = Integer.parseInt(cantidad_producto_txt.getText().trim());
                double val = rs.getDouble("valor_producto");
                double subt = val*cant;
                
                model.insertRow(con1,new Object[]{});
               
                
                model.setValueAt((id_producto_txt.getText().trim()), con1, 1);
                model.setValueAt((rs.getString("descripcion_producto")),con1,2);
                model.setValueAt((cantidad_producto_txt.getText().trim()), con1, 3);                
                model.setValueAt(rs.getString("valor_producto"), con1, 4);
                model.setValueAt((subt), con1, 6);
                
                
            con1++;
                
            } else {
                JOptionPane.showMessageDialog(this, "No existe el Producto");
            }
            
            int contar=lista_articulos_table.getRowCount();
            double suma=0;
            for(int i=0; i<contar;i++){
            suma=suma+Double.parseDouble(lista_articulos_table.getValueAt(i, 2).toString());
            String sum = Double.toString(suma);
            valor_total.setText(sum);
            }
            
            cantidad_producto_txt.setText(null);
            id_producto_txt.setText(null);
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JTextField cantidad_producto_txt;
    public static javax.swing.JLabel cedula;
    private javax.swing.JLabel clientetxt;
    public static javax.swing.JTextField doc_cliente_txt;
    private javax.swing.JLabel docutxt;
    public static com.toedter.calendar.JDateChooser fecha_venta;
    private javax.swing.JLabel fechatxt;
    private javax.swing.JLabel fechatxt1;
    private javax.swing.JTextField id_producto_txt;
    public static javax.swing.JLabel id_venta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable lista_articulos_table;
    public static javax.swing.JTextField nom_cliente_txt;
    private javax.swing.JTextField nom_producto_txt;
    private javax.swing.JTextField nombvend_txt;
    private javax.swing.JButton nuevaventa_btn;
    private javax.swing.JLabel pagotxt;
    private javax.swing.JComboBox<String> tipopago;
    public static javax.swing.JLabel valor_total;
    private javax.swing.JLabel vendtxt;
    // End of variables declaration//GEN-END:variables
}
