/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Antonio
 */
public class Familia extends javax.swing.JPanel {

    
    /**
     * Creates new form Principal
     */
    public Familia() {
        initComponents();
        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        button5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        button6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        button7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        codigo_familia = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        nombre_familia = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        descripción_familia = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        agregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        button3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mostrar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        button9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        button10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        button11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        button12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        button13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        modificar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        button15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Agregar, Buscar, Modificar y Mostrar Familias");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 800, -1));

        buscar.setBackground(new java.awt.Color(0, 204, 51));
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMousePressed(evt);
            }
        });
        buscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");
        buscar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 90, 30));

        button1.setBackground(new java.awt.Color(0, 204, 51));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar");
        button1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        buscar.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        button4.setBackground(new java.awt.Color(0, 204, 51));
        button4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button4MousePressed(evt);
            }
        });
        button4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar");
        button4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 80, 30));

        button5.setBackground(new java.awt.Color(0, 204, 51));
        button5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button5MousePressed(evt);
            }
        });
        button5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agregar");
        button5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        button4.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        buscar.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 140, 50));

        button6.setBackground(new java.awt.Color(0, 204, 51));
        button6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button6MousePressed(evt);
            }
        });
        button6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Agregar");
        button6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 80, 30));

        button7.setBackground(new java.awt.Color(0, 204, 51));
        button7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button7MousePressed(evt);
            }
        });
        button7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Agregar");
        button7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        button6.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        buscar.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, 50));

        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 150, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Id Familia");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 160, -1));

        codigo_familia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        codigo_familia.setForeground(new java.awt.Color(102, 102, 102));
        codigo_familia.setText("Ingrese el Id de la Familia");
        codigo_familia.setBorder(null);
        codigo_familia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codigo_familiaMousePressed(evt);
            }
        });
        codigo_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_familiaActionPerformed(evt);
            }
        });
        codigo_familia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_familiaKeyTyped(evt);
            }
        });
        add(codigo_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 330, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 330, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Nombre Familia");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 140, -1));

        nombre_familia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombre_familia.setForeground(new java.awt.Color(102, 102, 102));
        nombre_familia.setText("Ingrese el Nombre de la Familia");
        nombre_familia.setBorder(null);
        nombre_familia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombre_familiaMousePressed(evt);
            }
        });
        nombre_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_familiaActionPerformed(evt);
            }
        });
        nombre_familia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_familiaKeyTyped(evt);
            }
        });
        add(nombre_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 330, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 330, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Descripcion Familia");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 190, -1));

        descripción_familia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        descripción_familia.setForeground(new java.awt.Color(102, 102, 102));
        descripción_familia.setText("Ingrese la Descripcion de la Familia");
        descripción_familia.setBorder(null);
        descripción_familia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                descripción_familiaMousePressed(evt);
            }
        });
        descripción_familia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripción_familiaActionPerformed(evt);
            }
        });
        add(descripción_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 330, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 204, 51));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 330, 10));

        agregar.setBackground(new java.awt.Color(0, 204, 51));
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarMousePressed(evt);
            }
        });
        agregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Agregar");
        agregar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        button3.setBackground(new java.awt.Color(0, 204, 51));
        button3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button3MousePressed(evt);
            }
        });
        button3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregar");
        button3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        agregar.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 150, 50));

        mostrar.setBackground(new java.awt.Color(0, 204, 51));
        mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mostrarMousePressed(evt);
            }
        });
        mostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mostrar");
        mostrar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 90, 30));

        button9.setBackground(new java.awt.Color(0, 204, 51));
        button9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button9MousePressed(evt);
            }
        });
        button9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Agregar");
        button9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        mostrar.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        button10.setBackground(new java.awt.Color(0, 204, 51));
        button10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button10MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button10MousePressed(evt);
            }
        });
        button10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agregar");
        button10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 80, 30));

        button11.setBackground(new java.awt.Color(0, 204, 51));
        button11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button11MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button11MousePressed(evt);
            }
        });
        button11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Agregar");
        button11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        button10.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        mostrar.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 140, 50));

        button12.setBackground(new java.awt.Color(0, 204, 51));
        button12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button12MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button12MousePressed(evt);
            }
        });
        button12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Agregar");
        button12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 80, 30));

        button13.setBackground(new java.awt.Color(0, 204, 51));
        button13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button13MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button13MousePressed(evt);
            }
        });
        button13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Agregar");
        button13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        button12.add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        mostrar.add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, 50));

        add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 150, 50));

        modificar.setBackground(new java.awt.Color(0, 204, 51));
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarMousePressed(evt);
            }
        });
        modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Modificar");
        modificar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 10, 90, 30));

        button15.setBackground(new java.awt.Color(0, 204, 51));
        button15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button15MousePressed(evt);
            }
        });
        button15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Agregar");
        button15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        modificar.add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 180, 50));

        add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 150, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseEntered
    buscar.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_buscarMouseEntered

    private void buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseExited
    buscar.setBackground(new Color(0,204,51));        
    }//GEN-LAST:event_buscarMouseExited

    private void codigo_familiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigo_familiaMousePressed
    if (codigo_familia.getText().equals("Ingrese el Id de la Familia")) {
            codigo_familia.setText("");
            codigo_familia.setForeground(Color.black);
        }
    
    if (nombre_familia.getText().isEmpty()) {
            nombre_familia.setText("Ingrese el Nombre de la Familia");
            nombre_familia.setForeground(Color.gray);
        }
    
    if (descripción_familia.getText().isEmpty()) {
            descripción_familia.setText("Ingrese la Descripcion de la Familia");
            descripción_familia.setForeground(Color.gray);
        }
    
    
    }//GEN-LAST:event_codigo_familiaMousePressed

    private void codigo_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_familiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_familiaActionPerformed

    private void nombre_familiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_familiaMousePressed
    if (nombre_familia.getText().equals("Ingrese el Nombre de la Familia")) {
            nombre_familia.setText("");
            nombre_familia.setForeground(Color.black);
        }
    
    if (codigo_familia.getText().isEmpty()) {
            codigo_familia.setText("Ingrese el Id de la Familia");
            codigo_familia.setForeground(Color.gray);
        }
    
    if (descripción_familia.getText().isEmpty()) {
            descripción_familia.setText("Ingrese la Descripcion de la Familia");
            descripción_familia.setForeground(Color.gray);
        }
    
    
    }//GEN-LAST:event_nombre_familiaMousePressed

    private void nombre_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_familiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_familiaActionPerformed

    private void descripción_familiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descripción_familiaMousePressed
    if (descripción_familia.getText().equals("Ingrese la Descripcion de la Familia")) {
            descripción_familia.setText("");
            descripción_familia.setForeground(Color.black);
        }
    
    if (codigo_familia.getText().isEmpty()) {
            codigo_familia.setText("Ingrese el Id de la Familia");
            codigo_familia.setForeground(Color.gray);
        }
    
    if (nombre_familia.getText().isEmpty()) {
            nombre_familia.setText("Ingrese el Nombre de la Familia");
            nombre_familia.setForeground(Color.gray);
        }
    
    
    }//GEN-LAST:event_descripción_familiaMousePressed

    private void descripción_familiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripción_familiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripción_familiaActionPerformed

    // SUBIR
    private void buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMousePressed
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query ="select * from familia where id_familia = "+ Integer.parseInt(codigo_familia.getText().trim());
            
            ResultSet rs = con.consultar(query);
            
            if(rs.next()){
                nombre_familia.setText(rs.getString("nombre_familia"));
                descripción_familia.setText(rs.getString("descripcion_familia"));
            }
            else{
                JOptionPane.showMessageDialog(this, "No existe la Familia");
            }
            codigo_familia.setForeground(Color.black);
            nombre_familia.setForeground(Color.black);
            descripción_familia.setForeground(Color.black);
            
            con.cerrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarMousePressed

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MousePressed

    private void button3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button3MouseEntered

    private void button3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button3MouseExited

    private void button3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3MousePressed

    private void agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseEntered
    agregar.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_agregarMouseEntered

    private void agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseExited
    agregar.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_agregarMouseExited

    private void agregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMousePressed
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            String query ="insert into familia values("+ Long.parseLong(codigo_familia.getText().trim())+ ",'" + nombre_familia.getText().trim() + "','" + descripción_familia.getText().trim() +"')";
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            con.actualizar(query);
            
            con.cerrar();
            codigo_familia.setText(null);
            nombre_familia.setText(null);
            descripción_familia.setText(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_agregarMousePressed

    private void button5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button5MouseEntered

    private void button5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button5MouseExited

    private void button5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5MousePressed

    private void button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button4MouseEntered

    private void button4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button4MouseExited

    private void button4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4MousePressed

    private void button7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button7MouseEntered

    private void button7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button7MouseExited

    private void button7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button7MousePressed

    private void button6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button6MouseEntered

    private void button6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button6MouseExited

    private void button6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6MousePressed

    private void button9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button9MouseEntered

    private void button9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button9MouseExited

    private void button9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button9MousePressed

    private void button11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button11MouseEntered

    private void button11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button11MouseExited

    private void button11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button11MousePressed

    private void button10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button10MouseEntered

    private void button10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button10MouseExited

    private void button10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button10MousePressed

    private void button13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button13MouseEntered

    private void button13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button13MouseExited

    private void button13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button13MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button13MousePressed

    private void button12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button12MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button12MouseEntered

    private void button12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button12MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button12MouseExited

    private void button12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button12MousePressed

    private void mostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseEntered
    mostrar.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_mostrarMouseEntered

    private void mostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseExited
    mostrar.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_mostrarMouseExited
   
    private void mostrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMousePressed
    
    }//GEN-LAST:event_mostrarMousePressed

    private void button15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MouseEntered

    private void button15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MouseExited

    private void button15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MousePressed

    private void modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseEntered
    modificar.setBackground(new Color(102,255,0));
    }//GEN-LAST:event_modificarMouseEntered

    private void modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseExited
    modificar.setBackground(new Color(0,204,51));
    }//GEN-LAST:event_modificarMouseExited

    private void modificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMousePressed
        try {
            Conexion con = new Conexion();
            con.ConexionPostgres();
            
            String query ="update familia set nombre_familia = '"+nombre_familia.getText().trim()+"', descripcion_familia='"+descripción_familia.getText().trim()+"'where id_familia="+Long.parseLong(codigo_familia.getText().trim());
            JOptionPane.showMessageDialog(this, "Datos Actualizados");
            con.actualizar(query);
            
            con.cerrar();
            codigo_familia.setText(null);
            descripción_familia.setText(null);
            nombre_familia.setText(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Familia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarMousePressed

    private void mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarMouseClicked
    Familia_TE c = new Familia_TE();
    c.setSize(800, 500);
    c.setLocation(0, 0);
    
    escritorio.removeAll();
    escritorio.add(c, BorderLayout.CENTER);
    escritorio.revalidate();
    escritorio.repaint();      
    }//GEN-LAST:event_mostrarMouseClicked

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarMouseClicked

    private void codigo_familiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_familiaKeyTyped
    char c = evt.getKeyChar();
    if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_codigo_familiaKeyTyped

    private void nombre_familiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_familiaKeyTyped
    
    }//GEN-LAST:event_nombre_familiaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel agregar;
    private javax.swing.JPanel body;
    private javax.swing.JPanel buscar;
    private javax.swing.JPanel button1;
    private javax.swing.JPanel button10;
    private javax.swing.JPanel button11;
    private javax.swing.JPanel button12;
    private javax.swing.JPanel button13;
    private javax.swing.JPanel button15;
    private javax.swing.JPanel button3;
    private javax.swing.JPanel button4;
    private javax.swing.JPanel button5;
    private javax.swing.JPanel button6;
    private javax.swing.JPanel button7;
    private javax.swing.JPanel button9;
    private javax.swing.JTextField codigo_familia;
    private javax.swing.JTextField descripción_familia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel modificar;
    private javax.swing.JPanel mostrar;
    private javax.swing.JTextField nombre_familia;
    // End of variables declaration//GEN-END:variables
}
