/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author SENA
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rclientetxt = new javax.swing.JLabel();
        rproveedortxt = new javax.swing.JLabel();
        rproductotxt = new javax.swing.JLabel();
        rventastxt = new javax.swing.JLabel();
        rventasbtn = new javax.swing.JLabel();
        rproductobtn = new javax.swing.JLabel();
        rproveedorbtn = new javax.swing.JLabel();
        rclientebtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rclientetxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rclientetxt.setText("R.Clientes");
        getContentPane().add(rclientetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        rproveedortxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rproveedortxt.setText("R.Proveedores");
        getContentPane().add(rproveedortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        rproductotxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rproductotxt.setText("R.Productos");
        getContentPane().add(rproductotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        rventastxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rventastxt.setText("R.Ventas");
        getContentPane().add(rventastxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        rventasbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rventasbtn.png"))); // NOI18N
        getContentPane().add(rventasbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        rproductobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rproductosbtn.png"))); // NOI18N
        getContentPane().add(rproductobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        rproveedorbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rproveedoresbtn.png"))); // NOI18N
        getContentPane().add(rproveedorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        rclientebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rclientebtn.png"))); // NOI18N
        getContentPane().add(rclientebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoico5.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rclientebtn;
    private javax.swing.JLabel rclientetxt;
    private javax.swing.JLabel rproductobtn;
    private javax.swing.JLabel rproductotxt;
    private javax.swing.JLabel rproveedorbtn;
    private javax.swing.JLabel rproveedortxt;
    private javax.swing.JLabel rventasbtn;
    private javax.swing.JLabel rventastxt;
    // End of variables declaration//GEN-END:variables
}
