/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author SENA
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    public Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        docutxt = new javax.swing.JLabel();
        vendtxt = new javax.swing.JLabel();
        pagotxt = new javax.swing.JLabel();
        clientetxt = new javax.swing.JLabel();
        fechatxt = new javax.swing.JLabel();
        tipopago = new javax.swing.JComboBox<>();
        docindex = new javax.swing.JTextField();
        nombvend = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        buscarbtn = new javax.swing.JLabel();
        agregarbtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docutxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        docutxt.setText("DOCUMENTO");
        jPanel1.add(docutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        vendtxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vendtxt.setText("VENDEDOR");
        jPanel1.add(vendtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        pagotxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pagotxt.setText("PAGO");
        jPanel1.add(pagotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        clientetxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clientetxt.setText("CLIENTE");
        jPanel1.add(clientetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        fechatxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fechatxt.setText("FECHA");
        jPanel1.add(fechatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        tipopago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "CONTADO", "TJ CREDITO", "TJ DEBITO", "BONO" }));
        jPanel1.add(tipopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 129, 136, -1));

        docindex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        docindex.setForeground(new java.awt.Color(204, 204, 204));
        docindex.setText("ingrese la cc o nit");
        jPanel1.add(docindex, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 39, 136, -1));

        nombvend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombvend.setForeground(new java.awt.Color(204, 204, 204));
        nombvend.setText("nombre vendedor");
        jPanel1.add(nombvend, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 88, 136, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("nombre del cliente");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 39, 182, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 88, -1, -1));

        buscarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarventabtn.png"))); // NOI18N
        jPanel1.add(buscarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 39, 26, -1));

        agregarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarusuariobtn.png"))); // NOI18N
        jPanel1.add(agregarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 39, 26, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Cod del Articulo", "Descripcion", "Cantidad", "Precio", "Tipo Impuesto", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 172, 652, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoico5.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 740, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarbtn;
    private javax.swing.JLabel buscarbtn;
    private javax.swing.JLabel clientetxt;
    private javax.swing.JTextField docindex;
    private javax.swing.JLabel docutxt;
    private javax.swing.JLabel fechatxt;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nombvend;
    private javax.swing.JLabel pagotxt;
    private javax.swing.JComboBox<String> tipopago;
    private javax.swing.JLabel vendtxt;
    // End of variables declaration//GEN-END:variables
}
